package com.payflow.payflow.model;

import jakarta.persistence.*;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.sql.Timestamp;

/**
 * JPA Entity representing an employee's Cost to Company (CTC) details.
 * Each record tracks a specific salary structure that is effective from a certain date.
 * This entity is mapped to the `ctc_details` table in the database.
 */
@Entity
@Table(name = "ctc_details")
public class CTCDetails {

    /**
     * The unique identifier for the CTC record.
     * It is auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ctc_id")
    private Long ctcId;

    /**
     * The ID of the employee to whom this CTC record belongs.
     * This field is mandatory.
     */
    @Column(name = "employee_id", nullable = false)
    private Long employeeId;

    /**
     * The date from which this CTC structure becomes effective.
     * This field is mandatory.
     */
    @Column(name = "effective_from", nullable = false)
    private LocalDate effectiveFrom;

    /**
     * The date until which this CTC structure is effective.
     * A NULL value indicates the current, active CTC.
     */
    // Add this new field
    @Column(name = "effective_to")
    private LocalDate effectiveTo;

    /**
     * The basic salary component of the CTC.
     */
    @Column(name = "basic_salary")
    private BigDecimal basicSalary;

    /**
     * The House Rent Allowance component of the CTC.
     */
    @Column(name = "hra")
    private BigDecimal hra;

    /**
     * The general allowances component of the CTC.
     */
    @Column(name = "allowances")
    private BigDecimal allowances;

    /**
     * The bonuses component of the CTC.
     */
    @Column(name = "bonuses")
    private BigDecimal bonuses;

    /**
     * The Provident Fund (PF) contribution component.
     */
    @Column(name = "pf_contribution")
    private BigDecimal pfContribution;

    /**
     * The gratuity component of the CTC.
     */
    @Column(name = "gratuity")
    private BigDecimal gratuity;

    /**
     * The total CTC for the employee.
     */
    @Column(name = "total_ctc")
    private BigDecimal totalCTC;

    /**
     * The timestamp when this CTC record was created.
     */
    @Column(name = "created_at")
    private Timestamp createdAt;

    /**
     * The Dearness Allowance (DA) component of the CTC.
     */
    @Column(name = "da")
    private BigDecimal da;

    /**
     * The special allowance component of the CTC.
     */
    @Column(name = "special_allowance")
    private BigDecimal specialAllowance;

    // Constructors
    public CTCDetails() {
    }

    // Getters and Setters

    public Long getCtcId() {
        return ctcId;
    }

    public void setCtcId(Long ctcId) {
        this.ctcId = ctcId;
    }

    public Long getEmployeeId() {
        return employeeId;
    }

    public void setEmployeeId(Long employeeId) {
        this.employeeId = employeeId;
    }

    public LocalDate getEffectiveFrom() {
        return effectiveFrom;
    }

    public void setEffectiveFrom(LocalDate effectiveFrom) {
        this.effectiveFrom = effectiveFrom;
    }

    // Add the getter and setter for the new field
    public LocalDate getEffectiveTo() {
        return effectiveTo;
    }

    public void setEffectiveTo(LocalDate effectiveTo) {
        this.effectiveTo = effectiveTo;
    }

    public BigDecimal getBasicSalary() {
        return basicSalary;
    }

    public void setBasicSalary(BigDecimal basicSalary) {
        this.basicSalary = basicSalary;
    }

    public BigDecimal getHra() {
        return hra;
    }

    public void setHra(BigDecimal hra) {
        this.hra = hra;
    }

    public BigDecimal getAllowances() {
        return allowances;
    }

    public void setAllowances(BigDecimal allowances) {
        this.allowances = allowances;
    }

    public BigDecimal getBonuses() {
        return bonuses;
    }

    public void setBonuses(BigDecimal bonuses) {
        this.bonuses = bonuses;
    }

    public BigDecimal getPfContribution() {
        return pfContribution;
    }

    public void setPfContribution(BigDecimal pfContribution) {
        this.pfContribution = pfContribution;
    }

    public BigDecimal getGratuity() {
        return gratuity;
    }

    public void setGratuity(BigDecimal gratuity) {
        this.gratuity = gratuity;
    }

    public BigDecimal getTotalCTC() {
        return totalCTC;
    }

    public void setTotalCTC(BigDecimal totalCTC) {
        this.totalCTC = totalCTC;
    }

    public Timestamp getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    public BigDecimal getDa() {
        return da;
    }

    public void setDa(BigDecimal da) {
        this.da = da;
    }

    public BigDecimal getSpecialAllowance() {
        return specialAllowance;
    }

    public void setSpecialAllowance(BigDecimal specialAllowance) {
        this.specialAllowance = specialAllowance;
    }
}