package com.payflow.payflow.model;

import jakarta.persistence.*;
import java.math.BigDecimal;
import java.sql.Timestamp;

/**
 * JPA Entity representing an employee's payslip.
 * This class maps to the `payslip` table and stores details for a payslip
 * generated for a specific employee, month, and year.
 */
@Entity
@Table(name = "payslip")
public class Payslip {

    /**
     * The unique identifier for the payslip record.
     * It is auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "payslip_id")
    private Long payslipId;

    /**
     * The ID of the employee to whom this payslip belongs.
     * This field is mandatory.
     */
    @Column(name = "employee_id", nullable = false)
    private Long employeeId;

    /**
     * The month for which the payslip was generated (e.g., "January").
     */
    @Column(name = "month")
    private String month;

    /**
     * The year for which the payslip was generated.
     * This field is mandatory.
     */
    @Column(name = "year", nullable = false)
    private Integer year;

    /**
     * The final amount paid to the employee after all deductions.
     * This field is mandatory.
     */
    @Column(name = "net_pay", nullable = false)
    private BigDecimal netPay;

    /**
     * The total amount of deductions from the gross salary.
     */
    @Column(name = "deductions")
    private BigDecimal deductions;

    /**
     * The timestamp when the payslip was generated.
     */
    @Column(name = "generated_on")
    private Timestamp generatedOn;

    /**
     * A link to download the generated payslip document (e.g., a PDF).
     */
    @Column(name = "download_link")
    private String downloadLink;

    // Constructors
    public Payslip() {
    }

    // Getters and Setters

    public Long getPayslipId() {
        return payslipId;
    }

    public void setPayslipId(Long payslipId) {
        this.payslipId = payslipId;
    }

    public Long getEmployeeId() {
        return employeeId;
    }

    public void setEmployeeId(Long employeeId) {
        this.employeeId = employeeId;
    }

    public String getMonth() {
        return month;
    }

    public void setMonth(String month) {
        this.month = month;
    }

    public Integer getYear() {
        return year;
    }

    public void setYear(Integer year) {
        this.year = year;
    }

    public BigDecimal getNetPay() {
        return netPay;
    }

    public void setNetPay(BigDecimal netPay) {
        this.netPay = netPay;
    }

    public BigDecimal getDeductions() {
        return deductions;
    }

    public void setDeductions(BigDecimal deductions) {
        this.deductions = deductions;
    }

    public Timestamp getGeneratedOn() {
        return generatedOn;
    }

    public void setGeneratedOn(Timestamp generatedOn) {
        this.generatedOn = generatedOn;
    }

    public String getDownloadLink() {
        return downloadLink;
    }

    public void setDownloadLink(String downloadLink) {
        this.downloadLink = downloadLink;
    }
}
