package com.payflow.payflow.model;

import jakarta.persistence.*;

/**
 * JPA Entity representing a user in the PayFlow system.
 * This class handles authentication and authorization, storing
 * user credentials, role, and status.
 */
@Entity
public class User {

    /**
     * The unique identifier for the user.
     * It is auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The username for the user's account. This should be unique.
     */
    private String username;

    /**
     * The password for the user's account.
     */
    private String password;

    /**
     * The role of the user in the system (e.g., "ADMIN", "HR", "MANAGER").
     */
    private String role; // ADMIN, HR, MANAGER

    /**
     * The status of the user's account (e.g., "ACTIVE", "INACTIVE", "LOCKED").
     */
    private String status;

    /**
     * A flag indicating if the user is logging in for the first time.
     * New users must change their password on first login.
     * Defaults to `true`.
     */
    private boolean firstLogin = true;

    // Getters and Setters
    public Long getId() { return id; }
    public String getUsername() { return username; }
    public void setUsername(String username) { this.username = username; }

    public String getPassword() { return password; }
    public void setPassword(String password) { this.password = password; }

    public String getRole() { return role; }
    public void setRole(String role) { this.role = role; }

    public boolean isFirstLogin() { return firstLogin; }
    public void setFirstLogin(boolean firstLogin) { this.firstLogin = firstLogin; }

    public String getStatus() {
        return status;
    }
    public void setStatus(String status) {
        this.status = status;
    }
}
